export const commands = Object.freeze({
    ADD_USER: "ADD_USER",
    GET_USERS: "GET_USERS",
    GET_USER_MESSAGES: "GET_USER_MESSAGES",
    NEW_USER_MESSAGE: "NEW_USER_MESSAGE",
    SEND_USER_MESSAGE: "SEND_USER_MESSAGE"
});